# Generated by Django 2.2.2 on 2019-06-07 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mountain_log', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Mountain',
        ),
    ]
